name: 'maciej_project'
version: '1.0'

config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:

  maciej_project:

    staging:
      +materialized: view
      +schema: STAGING

    dimensions:
      +materialized: table
      +schema: DIM

    facts:
      +materialized: table
      +schema: FACT

    reporting:
      +materialized: view
      +schema: REPORTING
